// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      apikey: SUPABASE_PUBLISHABLE_KEY,
      eventsPerSecond: 10,
    },
    heartbeatIntervalMs: 15000,
  },
});

// ==========================================
// TEMPORARY DEV BYPASS (Due to Supabase Outage)
// ==========================================
const mockUser = {
  id: '00000000-0000-0000-0000-000000000000',
  email: 'dev@local.bypass',
  app_metadata: {},
  user_metadata: { username: 'BypassUser' },
  aud: 'authenticated',
  created_at: new Date().toISOString()
};

const mockSession = {
  access_token: 'mock-token',
  token_type: 'bearer',
  expires_in: 3600,
  refresh_token: 'mock-refresh',
  user: mockUser
};

supabase.auth.getSession = async () => {
  return { data: { session: mockSession }, error: null } as any;
};

supabase.auth.getUser = async () => {
  return { data: { user: mockUser }, error: null } as any;
};

supabase.auth.onAuthStateChange = (callback) => {
  setTimeout(() => callback('SIGNED_IN', mockSession as any), 0);
  return { data: { subscription: { unsubscribe: () => {} } } };
};
// ==========================================